export const Constants = {
  MODAL: {
    CONFIRM_REMOVE: 'MODAL_CONFIRM_REMOVE',
    CONFIRM_CHANGES: 'MODAL_CONFIRM_CHANGES',
  },
  ALERT: {
    SUCCESS: 'SUCCESS',
    SUCCESS_REMOVE: 'SUCCESS_REMOVE',
    GENERIC_ERROR: 'GENERIC_ERROR',
  }
}